export interface IUsuario {
  id: number,
  nome: string,
  genero: string,
  cpf: string,
  telefone: string,
  email: string,
  senha: string,
  tipo: string,
  matricula_Aluno: string,
  codigo_Registro_Professor: string,
  cep: string,
  cidade: string,
  uf: string,
  logradouro: string,
  numero: string,
  complemento: string,
  bairro: string,
  ponto_Referencia: string,
  empresa_Id: number
}
